___

<a href='https://mainacademy.ua/'> <img src='' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 4: Work with data professionally!

## Lab work 4

#### Мета: 

* навчитися обробляти дані
* "парсити" сайти

### Завдання 1:

#### Ознайомитися із API Національного банку 
https://bank.gov.ua/ua/

1. Підключитися до API.

In [1]:
import requests
import json
import pandas as pd

In [2]:
start = '20220101' 
end = '20221231'

url = f'https://bank.gov.ua/NBU_Exchange/exchange_site?start={start}&end=%20{end}&valcode=usd&sort=exchangedate&order=desc&json'

req = requests.get(url)

In [3]:
req

In [4]:
src = req.json()

2. Отримати курс долара за останній рік.

In [5]:
src

[{'exchangedate': '31.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.12.2022'},
 {'exchangedate': '30.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.12.2022'},
 {'exchangedate': '29.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '28.12.2022'},
 {'exchangedate': '28.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '27.12.2022'},
 {'exchangedate': '27.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '26.12.2022'},
 {'exchangedate': '26.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '23.12.2022'},
 {'exchangedate': '25.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '22.12.2022'},
 {'exchangedate': '24.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '22.12.2022'},
 {'exchangedate': '23.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '22.12.2022'},
 {'exchangedate': '22.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '21.12.2022'},
 {'exchangedate': '21.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '20.12.2022'},
 {'exchangedate': '20.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '19.12.2022'},
 {'exchangedate': '19.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '16.12.2022'},
 {'exchangedate': '18.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '15.12.2022'},
 {'exchangedate': '17.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '15.12.2022'},
 {'exchangedate': '16.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '15.12.2022'},
 {'exchangedate': '15.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '14.12.2022'},
 {'exchangedate': '14.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '13.12.2022'},
 {'exchangedate': '13.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '12.12.2022'},
 {'exchangedate': '12.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '09.12.2022'},
 {'exchangedate': '11.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '08.12.2022'},
 {'exchangedate': '10.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '08.12.2022'},
 {'exchangedate': '09.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '08.12.2022'},
 {'exchangedate': '08.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '07.12.2022'},
 {'exchangedate': '07.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '06.12.2022'},
 {'exchangedate': '06.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '05.12.2022'},
 {'exchangedate': '05.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '02.12.2022'},
 {'exchangedate': '04.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '01.12.2022'},
 {'exchangedate': '03.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '01.12.2022'},
 {'exchangedate': '02.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '01.12.2022'},
 {'exchangedate': '01.12.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '30.11.2022'},
 {'exchangedate': '30.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.11.2022'},
 {'exchangedate': '29.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '28.11.2022'},
 {'exchangedate': '28.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '25.11.2022'},
 {'exchangedate': '27.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '24.11.2022'},
 {'exchangedate': '26.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '24.11.2022'},
 {'exchangedate': '25.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '24.11.2022'},
 {'exchangedate': '24.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '23.11.2022'},
 {'exchangedate': '23.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '22.11.2022'},
 {'exchangedate': '22.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '21.11.2022'},
 {'exchangedate': '21.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '18.11.2022'},
 {'exchangedate': '20.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '17.11.2022'},
 {'exchangedate': '19.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '17.11.2022'},
 {'exchangedate': '18.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '17.11.2022'},
 {'exchangedate': '17.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '16.11.2022'},
 {'exchangedate': '16.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '15.11.2022'},
 {'exchangedate': '15.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '14.11.2022'},
 {'exchangedate': '14.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '11.11.2022'},
 {'exchangedate': '13.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '10.11.2022'},
 {'exchangedate': '12.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '10.11.2022'},
 {'exchangedate': '11.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '10.11.2022'},
 {'exchangedate': '10.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '09.11.2022'},
 {'exchangedate': '09.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '08.11.2022'},
 {'exchangedate': '08.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '07.11.2022'},
 {'exchangedate': '07.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '04.11.2022'},
 {'exchangedate': '06.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '03.11.2022'},
 {'exchangedate': '05.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '03.11.2022'},
 {'exchangedate': '04.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '03.11.2022'},
 {'exchangedate': '03.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '02.11.2022'},
 {'exchangedate': '02.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '01.11.2022'},
 {'exchangedate': '01.11.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '31.10.2022'},
 {'exchangedate': '31.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '28.10.2022'},
 {'exchangedate': '30.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '27.10.2022'},
 {'exchangedate': '29.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '27.10.2022'},
 {'exchangedate': '28.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '27.10.2022'},
 {'exchangedate': '27.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '26.10.2022'},
 {'exchangedate': '26.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '25.10.2022'},
 {'exchangedate': '25.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '24.10.2022'},
 {'exchangedate': '24.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '21.10.2022'},
 {'exchangedate': '23.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '20.10.2022'},
 {'exchangedate': '22.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '20.10.2022'},
 {'exchangedate': '21.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '20.10.2022'},
 {'exchangedate': '20.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '19.10.2022'},
 {'exchangedate': '19.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '18.10.2022'},
 {'exchangedate': '18.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '17.10.2022'},
 {'exchangedate': '17.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '14.10.2022'},
 {'exchangedate': '16.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '13.10.2022'},
 {'exchangedate': '15.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '13.10.2022'},
 {'exchangedate': '14.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '13.10.2022'},
 {'exchangedate': '13.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '12.10.2022'},
 {'exchangedate': '12.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '11.10.2022'},
 {'exchangedate': '11.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '10.10.2022'},
 {'exchangedate': '10.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '07.10.2022'},
 {'exchangedate': '09.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '06.10.2022'},
 {'exchangedate': '08.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '06.10.2022'},
 {'exchangedate': '07.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '06.10.2022'},
 {'exchangedate': '06.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '05.10.2022'},
 {'exchangedate': '05.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '04.10.2022'},
 {'exchangedate': '04.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '03.10.2022'},
 {'exchangedate': '03.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '30.09.2022'},
 {'exchangedate': '02.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.09.2022'},
 {'exchangedate': '01.10.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.09.2022'},
 {'exchangedate': '30.09.2022',
  'r030': 840,
  'cc': 'USD',
  'txt': 'Долар США',
  'enname': 'US Dollar',
  'rate': 36.5686,
  'units': 1,
  'rate_per_unit': 36.5686,
  'group': '1',
  'calcdate': '29.09.2022'},

3. Вивести середнє значення та відхилення курсу за кожний місяць.

In [6]:
dct = {
    'data': [],
    'rate': []
}

for i in range(len(src)):
    dct['data'].append(src[i]['exchangedate'])
    dct['rate'].append(src[i]['rate'])

In [7]:
df = pd.DataFrame(dct)

In [8]:
df.head()

         data     rate
0  31.12.2022  36.5686
1  30.12.2022  36.5686
2  29.12.2022  36.5686
3  28.12.2022  36.5686
4  27.12.2022  36.5686

In [9]:
df.dtypes

data     object
rate    float64
dtype: object

In [10]:
df.data = pd.to_datetime(df.data, format='%d.%m.%Y')

In [11]:
df.dtypes

data    datetime64[ns]
rate           float64
dtype: object

In [12]:
df['month_year'] = df.data.dt.strftime('%m-%Y')

In [13]:
df.head()

        data     rate month_year
0 2022-12-31  36.5686    12-2022
1 2022-12-30  36.5686    12-2022
2 2022-12-29  36.5686    12-2022
3 2022-12-28  36.5686    12-2022
4 2022-12-27  36.5686    12-2022

In [14]:
#Вивести середнє значення та відхилення курсу за кожний місяць.
df_rate = df.groupby('month_year').agg({'rate': ['mean','std']}).reset_index().reset_index() #середнє значення

In [15]:
df_rate

   index month_year       rate
                          mean       std
0      0    01-2022  27.981271  0.586451
1      1    02-2022  28.413664  0.462826
2      2    03-2022  29.254900  0.000000
3      3    04-2022  29.254900  0.000000
4      4    05-2022  29.254900  0.000000
5      5    06-2022  29.254900  0.000000
6      6    07-2022  31.850084  3.557190
7      7    08-2022  36.568600  0.000000
8      8    09-2022  36.568600  0.000000
9      9    10-2022  36.568600  0.000000
10    10    11-2022  36.568600  0.000000
11    11    12-2022  36.568600  0.000000

4. Дану інформацію записати у файл за допомогою pickle.

In [16]:
import pickle

In [17]:
with open('ForTeam.pkl', 'wb') as file:
    pickle.dump(df_rate, file)

In [18]:
#with open('ForTeam.pkl', 'rb') as file:
#    dct_test = pickle.load(file)

In [19]:
#dct_test

### Завдання 2:

Потрібно проаналізувати всі товари на сайті: 
https://smallpacking.agrosem.ua/

Створіть базу даних, що містить таблицю із такими стовбцями: 
    - артикул товару
    - найменування
    - ціна 
    - вага

In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from selenium) (0.23.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\tlehka\appdata\local\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [4]:
import requests
from bs4 import BeautifulSoup #пакет Python для анализа документов HTML и XML
from selenium import webdriver

In [5]:
url = 'https://smallpacking.agrosem.ua/products/?page=1'
req = requests.get(url)
soup = BeautifulSoup(req.text, 'html.parser')

In [17]:
#for i in range(1542, 2000):
for i in range(1542, 1545):
    
     url = f'https://smallpacking.agrosem.ua/products/{i}'
     req = requests.get(url)
     soup = BeautifulSoup(req.text, 'html.parser')
        
     #print(soup.find(class_='item_title'))
     for elem in soup.find_all(class_='item_title'):
        for elem2 in soup.find_all(class_='price'):    
            print(elem.text, elem2.text)
      
#Створіть базу даних, що містить таблицю із такими стовбцями: - артикул товару - найменування - ціна - вага

ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 799.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 1 220.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 1 230.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 3 070.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 3 030.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 348.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 799.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 799.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 348.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 348.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 799.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 799.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 348.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 14 240.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг 4 850.00 ₴
ДОБРИВО ДЛЯ ВІЧНОЗЕЛЕНИХ ДЕРЕВ ТА КУЩІВ ОСІНЬ 3 кг
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 1 220.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 1 230.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 3 070.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 3 030.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 14 240.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг 4 850.00 ₴
ДОБРИВО ДЛЯ ГАЗОНУ ВЕСНА-ЛІТО 1 кг
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 1 220.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 1 230.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 1 800.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 3 070.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 3 030.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 2 299.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 799.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 348.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 14 240.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 4 850.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг 8 370.00 ₴
ДОБРИВО ДЛЯ ОВОЧІВ 1 кг

In [25]:
dct={
    'item_title':[],
    'price':[]
}

for elem in soup.find_all(class_='item_title'):
    for elem2 in soup.find_all(class_='price'): 
        dct['item_title'].append(elem.text)
        dct['price'].append(elem2.text)

In [26]:
dct

{'item_title': ['ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг'],
 'price': ['348.00 ₴',
  '1 220.00 ₴',
  '1 230.00 ₴',
  '1 800.00 ₴',
  '1 800.00 ₴',
  '3 070.00 ₴',
  '3 030.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '14 240.00 ₴',
  '4 850.00 ₴',
  '8 370.00 ₴',
  ' ']}

In [27]:
tuple(dct.keys())

('item_title', 'price')

In [28]:
tuple(dct.values())

(['ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг'],
 ['348.00 ₴',
  '1 220.00 ₴',
  '1 230.00 ₴',
  '1 800.00 ₴',
  '1 800.00 ₴',
  '3 070.00 ₴',
  '3 030.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '14 240.00 ₴',
  '4 850.00 ₴',
  '8 370.00 ₴',
  ' '])

In [29]:
import pandas as pd

In [30]:
df=dct

In [31]:
df

{'item_title': ['ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг',
  'ДОБРИВО ДЛЯ ОВОЧІВ 1 кг'],
 'price': ['348.00 ₴',
  '1 220.00 ₴',
  '1 230.00 ₴',
  '1 800.00 ₴',
  '1 800.00 ₴',
  '3 070.00 ₴',
  '3 030.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '2 299.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '348.00 ₴',
  '799.00 ₴',
  '348.00 ₴',
  '14 240.00 ₴',
  '4 850.00 ₴',
  '8 370.00 ₴',
  ' ']}

In [ ]:
pd.DataFrame(df).to_excel('agrosem.xlsx', index=False)

In [32]:
import sqlite3

In [33]:
con = sqlite3.connect('agrosem.db')
curs = con.cursor()

In [34]:
curs.execute('''
    create table agrosemua (
    Name text,
    Price text
    )
''')

In [35]:
for name, price in zip(dct['item_title'], dct['price']):
    curs.execute(f"insert into agrosemua values ('{name}', '{price}')")

In [36]:
curs.execute('select * from agrosemua')
curs.fetchall()

[('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '1 220.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '1 230.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '1 800.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '1 800.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '3 070.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '3 030.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '799.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '2 299.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '799.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '2 299.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '799.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '799.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '348.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '14 240.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '4 850.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', '8 370.00 ₴'),
 ('ДОБРИВО ДЛЯ ОВОЧІВ 1 кг', ' ')]

### Завдання 3:

Ознайомтеся із роботою SQLite та відповідним модулем у Python.
Завантажте базу даних для виконання лабораторної роботи.
Підключіться до завантаженої бази SQLite.

1. Виведіть інформацію про дану базу.

In [69]:
import sqlite3 
import pandas as pd 
  
# create a connection 
con = sqlite3.connect('tysql.sqlite') 
data = pd.read_sql_query('SELECT name from sqlite_master where type= "table";', con)

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

2. Виведіть перелік всіх таблиць.

In [70]:
# show first 5 table names
data.head()

         name
0   Customers
1  OrderItems
2      Orders
3    Products
4     Vendors

3. Список всіх cust_id з таблиці Customers table.

In [78]:
result = pd.read_sql_query( 
'select distinct t.cust_id from Customers as t limit 2', con)
result

      cust_id
0  1000000001
1  1000000002

4. Всю таблицю Customers table

In [79]:
result = pd.read_sql_query( 
'select * from Customers as t limit 2', con)
result

,cust_id,cust_name,cust_address,cust_city,cust_state,cust_zip,cust_country,cust_contact,cust_email
0,1000000001,Village Toys,200 Maple Lane,Detroit,MI,44444,USA,John Smith,sales@villagetoys.com
1,1000000002,Kids Place,333 South Lake Drive,Columbus,OH,43333,USA,Michelle Green,None

5. Список клієнтів (cust_names) відсортованих від Z до A

In [88]:
result = pd.read_sql_query( 
'select t.cust_name from Customers as t order by t.cust_name desc', con)
result

       cust_name
0   Village Toys
1  The Toy Store
2     Kids Place
3        Fun4All
4        Fun4All

6. Таблицю клієнтів та замовлень (cust_id і order_num) . Відсортуйте по клієнту і потім по даті замовлення

In [99]:
result = pd.read_sql_query( 
'select * from Customers as c join Orders as o on c.cust_id=o.cust_id \
order by c.cust_id asc, o.order_num asc', con)
result

,cust_id,cust_name,cust_address,cust_city,cust_state,cust_zip,cust_country,cust_contact,cust_email,order_num,order_date,cust_id
0,1000000001,Village Toys,200 Maple Lane,Detroit,MI,44444,USA,John Smith,sales@villagetoys.com,20005,2012-05-01,1000000001
1,1000000001,Village Toys,200 Maple Lane,Detroit,MI,44444,USA,John Smith,sales@villagetoys.com,20009,2012-02-08,1000000001
2,1000000003,Fun4All,1 Sunny Place,Muncie,IN,42222,USA,Jim Jones,jjones@fun4all.com,20006,2012-01-12,1000000003
3,1000000004,Fun4All,829 Riverside Drive,Phoenix,AZ,88888,USA,Denise L. Stephens,dstephens@fun4all.com,20007,2012-01-30,1000000004
4,1000000005,The Toy Store,4545 53rd Street,Chicago,IL,54545,USA,Kim Howard,None,20008,2012-02-03,1000000005

7. Таблицю (на основі Items) з кількість та вартістю товару. Відсортуйте в порядку спадання по кількості та вартості

In [105]:
result = pd.read_sql_query( 
'select * from OrderItems as t order by t.quantity desc, t.item_price desc', con)
result

    order_num  order_item prod_id  quantity  item_price
0       20009           1  BNBG01       250        2.49
1       20009           2  BNBG02       250        2.49
2       20009           3  BNBG03       250        2.49
3       20005           2    BR03       100       10.99
4       20005           1    BR01       100        5.49
5       20007           2  BNBG01       100        2.99
6       20007           3  BNBG02       100        2.99
7       20007           4  BNBG03       100        2.99
8       20007           1    BR03        50       11.49
9       20007           5  RGAN01        50        4.49
10      20006           1    BR01        20        5.99
11      20006           3    BR03        10       11.99
12      20006           2    BR02        10        8.99
13      20008           3  BNBG01        10        3.49
14      20008           4  BNBG02        10        3.49
15      20008           5  BNBG03        10        3.49
16      20008           2    BR03         5       11.99
17      20008           1  RGAN01         5        4.99

8. Товар (з таблиці Products), ціна якого становить 9.49

In [110]:
result = pd.read_sql_query( 
'select * from Products as p where p.prod_price="9.49"', con)
result

,prod_id,vend_id,prod_name,prod_price,prod_desc
0,RYL01,FNG01,King doll,9.49,12 inch king doll with royal garments and crown
1,RYL02,FNG01,Queen doll,9.49,12 inch queen doll with royal garments and crown

9. Виведіть назву товару та ціну, яка лежить в діапазоні від  3 до 6. Відсортуйте результат в по ціні в порядку зростання

In [116]:
result = pd.read_sql_query( 
'select p.prod_name, p.prod_price from Products as p \
where p.prod_price between "3" and "6" order by p.prod_price asc', con)
result

             prod_name  prod_price
0    Fish bean bag toy        3.49
1    Bird bean bag toy        3.49
2  Rabbit bean bag toy        3.49
3          Raggedy Ann        4.99
4    8 inch teddy bear        5.99

10. Кількість товару, що було продано

In [131]:
# Customers OrderItems Orders Products Vendors
result = pd.read_sql_query( 
'select count(o.order_num) from Orders as o', con)
result

   count(o.order_num)
0                   5

11. Кількість найменувань товару, ціна якого більша за 4

In [137]:
result = pd.read_sql_query( 
'select count(p.prod_name) from Products as p where p.prod_price > "3" ', con)
result

   count(p.prod_name)
0                   9

12. Розробіть алгоритм для виведення 3 найдорожчих товарів в базі

In [141]:
result = pd.read_sql_query( 
'select p.prod_name, p.prod_price from Products as p order by p.prod_price desc limit 3', con)
result

            prod_name  prod_price
0  18 inch teddy bear       11.99
1           King doll        9.49
2          Queen doll        9.49

13. Підрахуйте кількість замовлень для кожного клієнта використовуючи підзапити

In [158]:
result = pd.read_sql_query ( 
'select c.cust_id, s.count_orders from Customers as c \
join\
(select o.cust_id,count(o.order_num) as count_orders from Orders as o group by o.cust_id) as s \
on c.cust_id=s.cust_id ', con)
result

      cust_id  count_orders
0  1000000001             2
1  1000000003             1
2  1000000004             1
3  1000000005             1

14. Виведіть список клієнтів та їх замовлення (використайте JOIN)

In [164]:
result = pd.read_sql_query( 
'select c.cust_name,o.order_num,o.order_date from Customers as c join Orders as o on c.cust_id=o.cust_id \
order by c.cust_id asc, o.order_num asc', con)
result

       cust_name  order_num  order_date
0   Village Toys      20005  2012-05-01
1   Village Toys      20009  2012-02-08
2        Fun4All      20006  2012-01-12
3        Fun4All      20007  2012-01-30
4  The Toy Store      20008  2012-02-03

15. Зробіть два запити: список товарів, ціна яких менша 5 та список товарів, ціна який більша рівна 5. Використайте UNION для об'єднання цих запитів

In [174]:
result = pd.read_sql_query( 
'select p.prod_name, "менше 5" as status from Products as p where p.prod_price < "5" \
union all select p.prod_name, "більше рівно 5" as status from Products as p where p.prod_price >= "5"', con)
result

             prod_name          status
0    Fish bean bag toy         менше 5
1    Bird bean bag toy         менше 5
2  Rabbit bean bag toy         менше 5
3          Raggedy Ann         менше 5
4    8 inch teddy bear  більше рівно 5
5   12 inch teddy bear  більше рівно 5
6   18 inch teddy bear  більше рівно 5
7            King doll  більше рівно 5
8           Queen doll  більше рівно 5

### Завдання 4:

Зареєструйтеся на сайті  https://www.hackerrank.com/

Виконайте 5 завданнь

Код запитів та короткий опис завдання вставляйте сюди

1 Query all columns for all American cities in the CITY table with populations larger than 100000. The CountryCode for America is USA.

The CITY table is described as follows:

`select*from city as s
where s.population > 100000
and s.countrycode='USA'`

2 Query all columns for a city in CITY with the ID 1661.

The CITY table is described as follows:
    
`select*from city as s
where s.id=1661`

3 Query the names of all the Japanese cities in the CITY table. The COUNTRYCODE for Japan is JPN.
The CITY table is described as follows:

`select s.name from city as s
where s.COUNTRYCODE='JPN'`

4 Query all attributes of every Japanese city in the CITY table. The COUNTRYCODE for Japan is JPN.

The CITY table is described as follows:

`select* from city as t
where t.countrycode='jpn'`

5 Query all columns (attributes) for every row in the CITY table.

The CITY table is described as follows:

`select * from city`